name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run Tests
      run: dotnet test --no-build --logger "trx;LogFileName=test_results.trx"

    - name: Publish Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: TestResults
        path: test_results.trx

    - name: Convert TRX to JUnit
      run: |
        dotnet tool install --global trx2junit
        TRX_FILE=$(find $(pwd) -name 'test_results.trx')
        echo "Found TRX file at: $TRX_FILE"
        trx2junit $TRX_FILE
      continue-on-error: true

    - name: Upload Test Report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: junit-results
        path: test_results.xml
