name: Publish NuGet Package

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Increment version number
      id: versioning
      run: |
        VERSION=$(cat ./DeckValidationService/DeckValidationService.csproj | grep -oPm1 "(?<=<Version>)[^<]+")
        NEW_VERSION=$(echo $VERSION | awk -F. -v OFS=. '{$NF++;print}')
        sed -i "s/<Version>$VERSION<\/Version>/<Version>$NEW_VERSION<\/Version>/" ./SecureDeck/SecureDeck.csproj
        echo "New version: $NEW_VERSION"
        echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV

    - name: Pack NuGet package
      run: dotnet pack ./DeckValidationService/DeckValidationService.csproj --configuration Release /p:PackageVersion=${{ env.VERSION }} --output ./package

    - name: Publish to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push ./package/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
